from django.db import models

class Laboratorio(models.Model):
    patient_id = models.IntegerField()
    nome = models.CharField(max_length=255, blank=True, null=True)
    nid = models.CharField(max_length=255, blank=True, null=True)
    sexo = models.CharField(max_length=2, blank=True, null=True)
    us_name = models.CharField(max_length=255, blank=True, null=True)
    data_inicio = models.DateTimeField(null=True, blank=True)
    data_pedido = models.CharField(null=True, blank=True)
    data_colheita = models.CharField(null=True, blank=True)
    data_resultado = models.CharField(null=True, blank=True)
    WBC = models.DecimalField(null=True, blank=True)
    RBC = models.DecimalField(null=True, blank=True)
    HGB_HB = models.DecimalField(null=True, blank=True)
    HCT_PCV = models.DecimalField(null=True, blank=True)
    HCV_VCM_VGM = models.DecimalField(null=True, blank=True)
    MCH_HGM_HCM = models.DecimalField(null=True, blank=True)
    MCHC_CHCM_CMHG = models.DecimalField(null=True, blank=True)
    PLT = models.DecimalField(null=True, blank=True)
    RDW = models.DecimalField(null=True, blank=True)
    VS_VHS = models.DecimalField(null=True, blank=True)
    MPV = models.DecimalField(null=True, blank=True)
    Tipagem_Sanguinea = models.DecimalField(null=True, blank=True)
    LYM_Percentual = models.DecimalField(null=True, blank=True)
    LYM_Absoluto = models.DecimalField(null=True, blank=True)
    NEUT_Percentual = models.DecimalField(null=True, blank=True)
    NEUT_Absoluto = models.DecimalField(null=True, blank=True)
    Eosinofilo_Percent = models.DecimalField(null=True, blank=True)
    Eosinofilo_Abs = models.DecimalField(null=True, blank=True)
    Basofilo_Percent = models.DecimalField(null=True, blank=True)
    Basofilo_Abs = models.DecimalField(null=True, blank=True)
    Monocito_Percent = models.DecimalField(null=True, blank=True)
    Monocito_Abs = models.DecimalField(null=True, blank=True)
    VDRL = models.DecimalField(null=True, blank=True)
    RPR = models.DecimalField(null=True, blank=True)
    cd4_absoluto = models.DecimalField(null=True, blank=True)
    cd4_percentual = models.DecimalField(null=True, blank=True)
    valor_carga = models.DecimalField(null=True, blank=True)
    qualidade_carga = models.DecimalField(null=True, blank=True)
    GeneXpert = models.DecimalField(null=True, blank=True)
    MTBdetectado = models.DecimalField(null=True, blank=True)
    nivelMTBdetectado = models.DecimalField(null=True, blank=True)
    Rifamoin = models.DecimalField(null=True, blank=True)
    Cultura = models.DecimalField(null=True, blank=True)
    TB_LAM = models.DecimalField(null=True, blank=True)
    CRAG = models.DecimalField(null=True, blank=True)
    baciloscopia = models.DecimalField(null=True, blank=True)
    NivelPositividade = models.DecimalField(null=True, blank=True)
    ALB = models.DecimalField(null=True, blank=True)
    AST_SGOT_GOT = models.DecimalField(null=True, blank=True)
    ALT_SGT_GPT = models.DecimalField(null=True, blank=True)
    AMI = models.DecimalField(null=True, blank=True)
    BIL = models.DecimalField(null=True, blank=True)
    COL = models.DecimalField(null=True, blank=True)
    HDL = models.DecimalField(null=True, blank=True)
    LDL = models.DecimalField(null=True, blank=True)
    Cr = models.DecimalField(null=True, blank=True)
    CK_CPK = models.DecimalField(null=True, blank=True)
    Fosfatase_Alcalina = models.DecimalField(null=True, blank=True)
    GGT = models.DecimalField(null=True, blank=True)
    GLC = models.DecimalField(null=True, blank=True)
    LDH = models.DecimalField(null=True, blank=True)
    Lactato = models.DecimalField(null=True, blank=True)
    Lipase = models.DecimalField(null=True, blank=True)
    Total_Proteina = models.DecimalField(null=True, blank=True)
    TG = models.DecimalField(null=True, blank=True)
    Ureia = models.DecimalField(null=True, blank=True)
    Cloreto = models.DecimalField(null=True, blank=True)
    Potassio = models.DecimalField(null=True, blank=True)
    Sodio = models.DecimalField(null=True, blank=True)
    Globulinas = models.DecimalField(null=True, blank=True)
    PCR = models.DecimalField(null=True, blank=True)
    
    def __str__(self):
        return f'{self.nome} {self.data_pedido}'
    

    
    